# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 15:41
from __future__ import unicode_literals

import core.models
import core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Custom label for url.', max_length=255)),
                ('uid', models.UUIDField(default=core.utils.short_url, editable=False, help_text='Short url identifier.', unique=True)),
                ('url', models.URLField(help_text='Destination url.')),
                ('custom_id', models.CharField(help_text='Custom short url identifier.', max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=models.SET(core.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
