# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 22:01
from __future__ import unicode_literals

import core.utils
from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=core.utils.short_url, editable=False, help_text='Short url identifier.', max_length=22, unique=True),
        ),
    ]
