# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 22:01
from __future__ import unicode_literals

import core.utils
from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=core.utils.create_uuid, editable=False, help_text='User public id.', max_length=22, unique=True),
        ),
    ]
